"""
Solution database models.
"""

from sqlalchemy import Column, String, Text, ForeignKey, Float, Table
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from .base import BaseModel

# Association table for solution components
solution_component_relationships = Table(
    'solution_component_relationships',
    BaseModel.metadata,
    Column('solution_id', UUID(as_uuid=True), ForeignKey('solutions.id'), primary_key=True),
    Column('component_id', UUID(as_uuid=True), ForeignKey('solution_components.id'), primary_key=True),
    Column('relationship_type', String(50))  # 'depends_on', 'conflicts_with', 'enhances'
)


class Solution(BaseModel):
    """Solutions generated by the Agent Orchestrator"""
    __tablename__ = 'solutions'
    
    problem_id = Column(UUID(as_uuid=True), ForeignKey('problems.id'), nullable=False)
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=False)
    approach = Column(Text, nullable=False)
    status = Column(String(20), default='draft')  # 'draft', 'review', 'approved', 'implemented'
    confidence_score = Column(Float, default=0.0)
    
    # Foreign keys
    created_by = Column(UUID(as_uuid=True), ForeignKey('users.id'))
    
    # Relationships
    problem = relationship("Problem", back_populates="solutions")
    components = relationship("SolutionComponent", back_populates="solution")


class SolutionComponent(BaseModel):
    """Components of a solution"""
    __tablename__ = 'solution_components'
    
    solution_id = Column(UUID(as_uuid=True), ForeignKey('solutions.id'), nullable=False)
    name = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    component_type = Column(String(100), nullable=False)
    priority = Column(String(20), default='medium')  # 'low', 'medium', 'high', 'critical'
    estimated_effort = Column(Float, default=0.0)  # in hours
    
    # Relationships
    solution = relationship("Solution", back_populates="components")
