"""
Solution domain models.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from .base import BaseModel


class Solution(BaseModel):
    """Represents a solution generated by the Cosmic Council"""
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.problem_id = kwargs.get('problem_id', '')
        self.title = kwargs.get('title', '')
        self.description = kwargs.get('description', '')
        self.approach = kwargs.get('approach', '')
        self.components = kwargs.get('components', [])
        self.implementation_plan = kwargs.get('implementation_plan', {})
        self.success_metrics = kwargs.get('success_metrics', [])
        self.status = kwargs.get('status', 'draft')
        self.confidence_score = kwargs.get('confidence_score', 0.0)
        self.created_by = kwargs.get('created_by')
    
    def validate(self) -> bool:
        """Validate solution data"""
        if not self.problem_id or not self.title or not self.description:
            return False
        if not isinstance(self.components, list):
            return False
        return True
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        base_dict = super().to_dict()
        return {
            **base_dict,
            'problem_id': self.problem_id,
            'title': self.title,
            'description': self.description,
            'approach': self.approach,
            'components': self.components,
            'implementation_plan': self.implementation_plan,
            'success_metrics': self.success_metrics,
            'status': self.status,
            'confidence_score': self.confidence_score,
            'created_by': self.created_by
        }


class SolutionComponent(BaseModel):
    """Represents a component of a solution"""
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.solution_id = kwargs.get('solution_id', '')
        self.name = kwargs.get('name', '')
        self.description = kwargs.get('description', '')
        self.component_type = kwargs.get('component_type', '')
        self.dependencies = kwargs.get('dependencies', [])
        self.resources_required = kwargs.get('resources_required', {})
        self.estimated_effort = kwargs.get('estimated_effort', 0)
        self.priority = kwargs.get('priority', 'medium')
    
    def validate(self) -> bool:
        """Validate solution component"""
        return bool(self.solution_id and self.name and self.description)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        base_dict = super().to_dict()
        return {
            **base_dict,
            'solution_id': self.solution_id,
            'name': self.name,
            'description': self.description,
            'component_type': self.component_type,
            'dependencies': self.dependencies,
            'resources_required': self.resources_required,
            'estimated_effort': self.estimated_effort,
            'priority': self.priority
        }
