apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "cosmic-council-logs-*"
    isDefault: false
    editable: true
    jsonData:
      index: "cosmic-council-logs-*"
      timeField: "@timestamp"
      esVersion: "7.17.0"
      logMessageField: "message"
      logLevelField: "level"
