"""
Core type definitions and enums for the Cosmic Council system.
"""

from enum import Enum
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime, timezone
import uuid


class EnterpriseType(Enum):
    """The six enterprises of the Cosmic Council"""
    RED_OWL = "red_owl"                    # Research & Discovery
    ORANGE_ORANGUTAN = "orange_orangutan"  # Planning & Strategy
    YELLOW_HONEYBEE = "yellow_honeybee"    # Development & Implementation
    GREEN_TORTOISE = "green_tortoise"      # Budget & Resources
    BLUE_DOLPHIN = "blue_dolphin"          # Market & Communication
    PURPLE_ELEPHANT = "purple_elephant"    # Support & Feedback


class ProblemComplexity(Enum):
    """Problem complexity levels"""
    SIMPLE = "simple"
    MODERATE = "moderate"
    COMPLEX = "complex"
    SYSTEMIC = "systemic"


class CycleStatus(Enum):
    """Cycle execution status"""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    PAUSED = "paused"


class AgentStatus(Enum):
    """Agent execution status"""
    IDLE = "idle"
    ACTIVE = "active"
    PROCESSING = "processing"
    ERROR = "error"
    OFFLINE = "offline"


class WorkflowStatus(Enum):
    """Workflow execution status"""
    DRAFT = "draft"
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class ProblemStatement:
    """Represents a problem to be solved by the Cosmic Council"""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    title: str = ""
    description: str = ""
    complexity: ProblemComplexity = ProblemComplexity.MODERATE
    domain: str = ""
    stakeholders: List[str] = field(default_factory=list)
    constraints: Dict[str, Any] = field(default_factory=dict)
    success_criteria: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Solution:
    """Represents a solution generated by the Cosmic Council"""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    problem_id: str = ""
    title: str = ""
    description: str = ""
    approach: str = ""
    components: List[Dict[str, Any]] = field(default_factory=list)
    implementation_plan: Dict[str, Any] = field(default_factory=dict)
    success_metrics: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Cycle:
    """Represents a problem-solving cycle"""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    problem_id: str = ""
    status: CycleStatus = CycleStatus.PENDING
    enterprises: List[EnterpriseType] = field(default_factory=list)
    current_enterprise: Optional[EnterpriseType] = None
    results: Dict[str, Any] = field(default_factory=dict)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = field(default_factory=dict)
