#!/usr/bin/env bash

# Dream Caesar workstation integration for the local AI stack.
# Source this from an interactive shell or from launcher scripts.

if [ -f "$HOME/.config/ai-dev/env.sh" ]; then
  # shellcheck disable=SC1090
  . "$HOME/.config/ai-dev/env.sh"
fi

export DREAM_CAESAR_ROOT="${DREAM_CAESAR_ROOT:-$HOME/dream-caesar}"
export DREAM_CAESAR_RUNTIME_ROOT="${DREAM_CAESAR_RUNTIME_ROOT:-${AI_STACK_ROOT:-/mnt/storage/AI}/apps/dream-caesar}"
export DREAM_CAESAR_DESKTOP_COUNCIL_ROOT="${DREAM_CAESAR_DESKTOP_COUNCIL_ROOT:-$DREAM_CAESAR_RUNTIME_ROOT/desktop-council}"
export DREAM_CAESAR_ARTIFACTS="${DREAM_CAESAR_ARTIFACTS:-$DREAM_CAESAR_DESKTOP_COUNCIL_ROOT/artifacts}"
export DREAM_CAESAR_ARTIFACT_ROOT="${DREAM_CAESAR_ARTIFACT_ROOT:-$DREAM_CAESAR_ARTIFACTS}"
export DREAM_CAESAR_HANDOFF_DIR="${DREAM_CAESAR_HANDOFF_DIR:-$DREAM_CAESAR_DESKTOP_COUNCIL_ROOT/handoffs}"
export DREAM_CAESAR_HANDOFF_ROOT="${DREAM_CAESAR_HANDOFF_ROOT:-$DREAM_CAESAR_HANDOFF_DIR}"
export DREAM_CAESAR_MAIL_ROOT="${DREAM_CAESAR_MAIL_ROOT:-$DREAM_CAESAR_DESKTOP_COUNCIL_ROOT/mail}"
export DREAM_CAESAR_ACTIVE_CANON_PATH="${DREAM_CAESAR_ACTIVE_CANON_PATH:-$DREAM_CAESAR_DESKTOP_COUNCIL_ROOT/active-canon.json}"
export DREAM_CAESAR_CACHE="${DREAM_CAESAR_CACHE:-$DREAM_CAESAR_RUNTIME_ROOT/cache}"
export DREAM_CAESAR_LOGS="${DREAM_CAESAR_LOGS:-$DREAM_CAESAR_RUNTIME_ROOT/logs}"
export DREAM_CAESAR_DB_DIR="${DREAM_CAESAR_DB_DIR:-$DREAM_CAESAR_RUNTIME_ROOT/data}"
export DREAM_CAESAR_DB_PATH="${DREAM_CAESAR_DB_PATH:-$DREAM_CAESAR_DB_DIR/dream_caesar.db}"
export DREAM_CAESAR_RECOVERY_ROOT="${DREAM_CAESAR_RECOVERY_ROOT:-$DREAM_CAESAR_RUNTIME_ROOT/recovery}"

export API_HOST="${API_HOST:-127.0.0.1}"
export API_PORT="${API_PORT:-8012}"
export CRONUS_API_HOST="${CRONUS_API_HOST:-127.0.0.1}"
export CRONUS_API_PORT="${CRONUS_API_PORT:-8010}"
export FRONTEND_PORT="${FRONTEND_PORT:-3000}"
export ALLOW_ANONYMOUS="${ALLOW_ANONYMOUS:-true}"

export OLLAMA_MODEL="${OLLAMA_MODEL:-gpt-oss:20b}"
export OLLAMA_HOST="${OLLAMA_HOST:-http://localhost:11434}"
export OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-$OLLAMA_HOST}"
export LLM_MODEL="${LLM_MODEL:-$OLLAMA_MODEL}"
export LOCAL_BASE_URL="${LOCAL_BASE_URL:-$OLLAMA_BASE_URL}"
export LOCAL_MODEL="${LOCAL_MODEL:-$OLLAMA_MODEL}"

export CRONUS_LLM_MODEL="${CRONUS_LLM_MODEL:-$OLLAMA_MODEL}"
export CRONUS_LLM_BASE_URL="${CRONUS_LLM_BASE_URL:-$OLLAMA_HOST/v1}"
export CRONUS_LLM_API_KEY="${CRONUS_LLM_API_KEY:-ollama}"
export CRONUS_ENV_FILE="${CRONUS_ENV_FILE:-$DREAM_CAESAR_ROOT/CRONUS/.env.local}"

export HF_HOME="${HF_HOME:-${AI_STACK_ROOT:-/mnt/storage/AI}/cache/huggingface}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
export UV_CACHE_DIR="${UV_CACHE_DIR:-${AI_STACK_ROOT:-/mnt/storage/AI}/cache/uv}"

mkdir -p \
  "$DREAM_CAESAR_RUNTIME_ROOT" \
  "$DREAM_CAESAR_DESKTOP_COUNCIL_ROOT" \
  "$DREAM_CAESAR_ARTIFACTS" \
  "$DREAM_CAESAR_HANDOFF_DIR" \
  "$DREAM_CAESAR_MAIL_ROOT" \
  "$DREAM_CAESAR_CACHE" \
  "$DREAM_CAESAR_LOGS" \
  "$DREAM_CAESAR_DB_DIR" \
  "$DREAM_CAESAR_RECOVERY_ROOT"

export DATABASE_URL="${DATABASE_URL:-sqlite+aiosqlite:///$DREAM_CAESAR_DB_PATH}"
